### PR TITLE
Update PHP to 7.0.14

### PR DESCRIPTION
**Pull request by NycuRO**

### CODE REVIEW

**Comment by dktapps** [comment]
This is not a contribution, merely a change of a number.

**Comment by NycuRO** [comment]
@dktapps You can add 7.0.14?

**Comment by dktapps** [comment]
It's preferable if you were to submit an issue for this kind of thing instead, since it is just a number. Yes, I can update it.

**Comment by NycuRO** [comment]
Ok ,thanks so much for update.

**Pull request closed without merging**
