### PR TITLE
Removed wxwidget and updated PHP version to 7.0.12

### PR DESCRIPTION
**Pull request by legoboy0215**
I have tested this and it works. OpenSSL may be needed in the future, so I commented it. But if you want me to remove it, I can.

### CODE REVIEW

**Comment by dktapps** [comment]
Why make another PR when the changes are already in this one?

**Comment by legoboy0215** [comment]
Oops sorry. The other PR was for the compile.sh script. I'll commit here.

**Comment by legoboy0215** [comment]
Can anyone close or merge?

**Comment by legoboy0215** [comment]
Finally :P Thanks.

**Pull request merged**
