### PR TITLE
Update DS version

### PR DESCRIPTION
**Pull request by Frago9876543210**
Due to the fact that the PM began to demand DS 1.2.7 need to update commit

### CODE REVIEW

**Comment by dktapps** [comment]
The existing version references this one: https://github.com/php-ds/ext-ds/commit/4bb4be24ce9835ca81be2e48f0104683e41bce12

I don't want to use untagged code if it can be avoided.

**Comment by Frago9876543210** [comment]
Well, try install composer with binary from jenkins

**Comment by dktapps** [comment]
Yes, the binaries on Jenkins are out of date. The scripts are fine though.

**Comment by Frago9876543210** [comment]
default

**Pull request closed without merging**
