### PR TITLE
Fix path of composer.bat

### PR DESCRIPTION
**Pull request by fuyutsuki**
I modified the path of composer.bat so that it works normally.

### CODE REVIEW

**Comment by fuyutsuki** [comment]
@dktapps Why is it invalid?

**Comment by dktapps** [comment]
it already works as intended.

**Comment by fuyutsuki** [comment]
No, it will not work.
I made the following file structure and executed composer.bat, but only output of composer usage is output.

### File structure
```
\
| -- bin
|      | -- php
|      | -- composer.bat
|      \ -- composer.phar
| -- PocketMine-MP.phar
| -- start.bat
```

### Output
```bash
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.5.2 2017-09-11 16:59:25

Usage:
~~~
```

**Comment by dktapps** [comment]
that's because you're using it incorrectly. You're executing it from the wrong place, and not providing sufficient arguments.

`bin/composer install`

**Comment by fuyutsuki** [comment]
How do I correctly arrange the files?

**Comment by fuyutsuki** [comment]
1. Download and extract binary from AppVeyor`s latest build.
2. Download and extract PocketMine-MP source from pmmp/PocketMine-MP repo.
3. Install as above and run composer.bat
What is wrong?

**Comment by dktapps** [comment]
> `bin/composer install`

**Comment by fuyutsuki** [comment]
Do I need to execute the command at installation time?
If so, this pull request is for omitting it.

**Comment by fuyutsuki** [comment]
Is it unnecessary?

**Pull request closed without merging**
